### ISSUE TITLE
[question] why not return the whole contact record?

### ISSUE THREAD

**Issue by janl** [rhaker/react-native-select-contact-name-ios#2]
Heya.

I’m looking at these very useful modules of the react-native-select-contact-*-ios variety, thank you for your hard work here!

I’m noticing you’ve got one for some of the more common parts of a contact.

I’m wondering, why didn’t you decide to return the whole contacts object instead of the -name, -address, etc?

Best!
Jan

**Comment by rhaker** [comment]
Thanks for the question and trying out the module!

When I first starting building these (after RN was just released), I was trying to keep things modular and simple. There were so many different fields that could be returned for a contact (and I only needed a few for my project at the time), that I thought people would keep asking to have me add fields (if I only included just a few). So instead, I decided to build them this way. I took a different approach with the select-contact-android module.

For what it's worth, I provide directions for combining all the modules here (https://github.com/rhaker/react-native-select-contact-phone-ios/issues/5). It's super easy to mix them - just a copy and paste a few lines of code.

All the best!
